#!/bin/bash
#
# DoSH - Docker SHell
# https://github.com/grycap/dosh
#
# Copyright (C) GRyCAP - I3M - UPV 
# Developed by Carlos A. caralla@upv.es
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# -------------------------------------------------------------------------
#
# This script connects the container that has been just started to the network
#  in the variable NEWNETWORK
#
NEWNETWORK=myextranetwork

COMMAND=$1
CONTAINER=$2
shift
shift

case "$COMMAND" in
  prerun)
    ;;
  run)
    docker network connect "$NEWNETWORK" "$CONTAINER"
    ;;
  prestart) 
    ;;
  start) 
    ;;
  preexec) 
    # Ensure that the container is connected to the network (e.g. this
    # script has been activated after the container has been created)
    VALUE="$(docker inspect -f "{{.NetworkSettings.Networks.$NEWNETWORK.NetworkID }}" "$CONTAINER")"
    if [ "$VALUE" == "<no value>" ]; then
      docker network connect "$NEWNETWORK" "$CONTAINER"
    fi
    ;;
  exec) 
    ;;
  *)
    echo "unexpected command" >&2
    ;;
esac