#!/bin/bash
#
# DoSH - Docker SHell
# https://github.com/grycap/dosh
#
# Copyright (C) GRyCAP - I3M - UPV 
# Developed by Carlos A. caralla@upv.es
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# -------------------------------------------------------------------------
#
# This is a template for the scripts that are triggered upon the occurrence 
# of docker calls.
#   If you want to use it, please copy it and make your customizations. Then 
#   make sure that the script has +x permissions in order to be able to be used 
#   (otherwise it will not be executed).
# Each command has information about when it is invoked and the parameter that 
#   it gets.

COMMAND=$1
CONTAINER=$2
shift
shift

case "$COMMAND" in
  prerun)
    # called before the container is created
    #  $@: the parameters to the docker run call that is being executed
    ;;
  run)
    # called after the container has been created
    #  $@: the parameters to the docker run call that has been executed
    ;;
  prestart) 
    # called before the container is started (if it was stopped)
    #  * no parameteres
    ;;
  start) 
    # called after the container has been started (if it was stopped)
    #  * no parameteres
    ;;
  preexec) 
    # called before the user gets the session in the container
    #  $1: the shell that is being used to run the container
    ;;
  exec) 
    # called after the user leaves the session in the container
    #  $1: the shell that has been used to run the container
    ;;
  *)
    echo "unexpected command" >&2
    ;;
esac